### PR TITLE
Update Loader for DirectX Animated models

### PR DESCRIPTION
**Pull request by yazancash**
Hello Jey

XLoader is very useful addon for ThreeJS, and i find DirectX format is classic and primary for a lot of developers.

I would like if XLoader can be working correctly with animation of DirectX 9.0+ format, this will save a lot of time.

Or -another solution-
i like to find a function to convert DirectX models into JSON format, then we can load JSON data with animation into ThreeJS.

Thanks for your time!
Regards

### CODE REVIEW

**Comment by yazancash** [comment]
maybe the problem in Animation is because model is multi-textures ?
maybe WebGL split model into different parts for each texture.
so i think it's better to try with Single texture model first.

**Comment by adrs2002** [comment]
Thank you for your cooporation!
It is not a problem that the model is multi-textured. Loading of models that do not animate as per the image is done without problems.

[http://www001.upp.so-net.ne.jp/adrs2002/tmp1.png](http://www001.upp.so-net.ne.jp/adrs2002/tmp1.png)

It is obvious that the problem lies in the bone part of the animation and I try to solve it.

**Comment by adrs2002** [comment]
There is a little doubt.
I have [paul4u.x], there are too many missing data. For example, [BaseBody] and [mixamorig_HeadTop_End] exist as animation keys, but because they do not have bone information (skinWeight), they can not be moved. Have you edited this file manually?

**Comment by adrs2002** [comment]
maybe IK...? As expected it can not cope with my skills

**Comment by yazancash** [comment]
i look at screenshot you gave
http://www001.upp.so-net.ne.jp/adrs2002/tmp1.png

i find Bone is not identical with body, as i know this causes big problems in animations.

can you tell me how can i get this result, to see Body static and Bone visible.
so i can do changes in bone position/rotation hopefully this solves the problem.

so, let me know how can i get the image you gave above?

**Comment by yazancash** [comment]
regarding the loss in (skinWeight) data, this is not a problem, bones should animate correctly and some bones has No points attached to, so there is no (skinWeight) for some bones, i find this normal.

but the problem is, Bone is not standing correctly, i find i should change [Hips] (the base bone) position and rotation, hopefully this solves.
**at least, i want to see the bones animating correctly, regardless the body.**

**Comment by yazancash** [comment]
i tried to correct [Hips] position to be identical with mesh body, please try this:
https://www.dropbox.com/s/smnw5uztf6qeomq/TEPO6YYDVIAJO5TCDWVDFYN7G_xAnim-running.zip?dl=0

**Comment by adrs2002** [comment]
thanks for edit your data!
I prepared a sample showing the model without animation.
[http://www001.upp.so-net.ne.jp/adrs2002/xloader/xfileTest2.html](http://www001.upp.so-net.ne.jp/adrs2002/xloader/xfileTest2.html)

I will confirm the data you receive from now. please wait.

**Comment by yazancash** [comment]
i see Bones are not set correctly.
[https://postimg.org/image/rpq0jri27/](https://postimg.org/image/rpq0jri27/)
when bones standing and moving correctly, everything should be good.

**Comment by yazancash** [comment]
i'm testing Bones by using T-pose short animation.

i find only half of bones showing.
screenshot:
[https://postimg.org/image/g4mvdj7rr/](https://postimg.org/image/g4mvdj7rr/)

i find we should solve Bones animation first, then we focus on mesh body.

test files here:
[https://www.dropbox.com/s/14o3ijta8nuccsp/Tpose%20Test.zip?dl=0](https://www.dropbox.com/s/14o3ijta8nuccsp/Tpose%20Test.zip?dl=0)

**Comment by yazancash** [comment]
i made deeper tests, i think something wrong here

```
 Animation Animation2 {
      {mixamorig_Spine1}
      AnimationKey {
       2;
       18;
       0; 3; 0.000000,  0.180877,  0.000000;;,
       1; 3; 0.000000,  0.180877,  0.000000;;,
```

```
 Animation Animation3 {
      { mixamorig_Spine2 }
      AnimationKey {
       2;
       18;
       0; 3; 0.000000, 0.163332,  0.000000;;,
       1; 3; 0.000000, 0.163332,  0.000000;;,
```

you can see,
Spine1 has position.y = 0.180877
Spine2 has position.y = 0.163332

your loader reading values as Absolute, but it should be Relative.
so that
Spine2 should be position.y = [root].y + [hips].y + [spine].y + 0.180877 + 0.163332

i hope this is clear, and please check email i sent.

**Comment by adrs2002** [comment]
I am sorry I made you wait.

I extended the sample to investigate the problem.
http://www001.upp.so-net.ne.jp/adrs2002/xloader/xfileTest2.html

Press [ View Bone Tree ( on your Upper right corner) ] button to check the configuration of bone ｃonstitution.
Due to some problem, waist bone is missing from parentage relationship.

I will investigate whether it is a source problem or data problem. I am sorry for taking time.

**Comment by adrs2002** [comment]
OK.
I fixed the model data .
https://www.dropbox.com/s/y7egbpjwvc3oeg7/xloader_editing.zip?dl=0

[Bone] needs to be a child hierarchy of [mesh].
In the first data, [Mesh] was a child of [mixamorig_Spine].
[Body 0] and [_ Hips] above that have fallen out.

**Comment by adrs2002** [comment]
However, in [paul] it is correctly structured.
There is no difference in the fact that there is a mistake in my program.
Right now, I am looking at the material of the long time ago [X-file]. I feel a little bad feeling.

**Comment by yazancash** [comment]
Great progress, thank you!
here i attached Running animation instead of Tpose, i find bones are showing correctly and coincident to mesh body.
https://www.dropbox.com/s/3e433c9cwop5ssv/Running.zip?dl=0

i think, if you try to apply animation, it works with something wrong around these

```
Animation Animation2 {
      { mixamorig_Spine1 }
      AnimationKey {
       2;
       18;
       0; 3; 0.000000, 0.180877,  0.000000;;,
       1; 3; 0.000000, 0.180877,  0.000000;;,
        .........etc
```

and

```
 Animation Animation3 {
      { mixamorig_Spine2 }
      AnimationKey {
       2;
       18;
       0; 3; 0.000000, 0.163332,  0.000000;;,
       1; 3; 0.000000, 0.163332,  0.000000;;,
        .........etc
```

i feel, the loader is applying values on key frames by an Absolute values, example it set Spine2 at position.y = 0.163332
but it should be relative to parent frame, so it should be = Spine1.y + 0.163332
i think it does not add position of parent frame. (i'm not sure)

anyway i find there is a Great progress forward.

**Comment by yazancash** [comment]
maybe these help you:
http://www.cgdev.net/blog/468.html
http://www.cgdev.net/blog/471.html

if we can convert DirectX to Json format, problem being solved.

**Comment by adrs2002** [comment]
>i think it does not add position of parent frame. (i'm not sure)

They are called "inverse matrix", and three.js creates them automatically. (Specifically, it is right after setting skeleton).
In key frame animation, only "change amount" from the base-Matrix is described.
It is desirable that the base-Matrix is like Tpose.

It is quite interesting to change X file to Json file and output it. I will spend some time preparing this week.

**Pull request closed without merging**
